name: Build Python Artifact

on:
  push:
    branches: [ main, dev, feature/** ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build sdist and wheel
        run: |
          python -m build
          ls -l dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: devops-ecommerce-dist
          path: dist/*
          if-no-files-found: error
