name: E-Commerce CI

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-test-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            src/ecommerce/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f src/ecommerce/requirements.txt ]; then pip install -r src/ecommerce/requirements.txt; fi
          pip install pytest flake8 black isort mypy bandit pytest-mock

      - name: Lint with flake8
        run: flake8 src tests

      - name: Check code formatting (black)
        run: black --check src tests

      - name: Check import order (isort)
        run: isort --check-only src tests

      - name: Static type checks (mypy)
        run: mypy src

      - name: Security scan (bandit)
        run: bandit -r src/ecommerce -x tests -q

      - name: Run Unit Tests
        env:
          PYTHONPATH: src
        run: pytest tests/ -v --tb=short

      - name: Run Integration Tests
        env:
          PYTHONPATH: src
        run: pytest tests/integration/ -v --tb=short
